name: go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Set up Go 1.20.3
      uses: actions/setup-go@v4
      with:
        go-version: ^1.20.3

    - name: Install dependencies
      run: go mod download

    - name: Build
      run: make build

    - name: Test
      run: make test
